/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Shalmon (https://sketchfab.com/nashalanandas)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/building-03-c76ac44df995482185077da81939b306
title: Building 03
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/building03.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 3, 0]}>
          <group position={[-6.80, -2.2, 1.8]} scale={[0.85, 0.040, 1]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['building3.002']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_15.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_19.geometry} material={materials.building3} />
            <mesh geometry={nodes.Object_20.geometry} material={materials['building3.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/building03.gltf')
