/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ChamberSu1996 (https://sketchfab.com/chambersu1996)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/haveto-the-parent-of-the-glasses-chibi-ver-504489d8f1924a449c641719ab78b95f
title: Haveto: the parent of The Glasses Chibi Ver
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/parent.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[150, 0, -1150]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={107.5}>
            <mesh geometry={nodes.BoyBody001_ProceduralSkin_0.geometry} material={materials.ProceduralSkin} />
          </group>
          <group position={[149.15, 0.39, -1158.74]} rotation={[-1.47, 0.01, 1.8]} scale={107.5}>
            <mesh geometry={nodes.Brow002_VertexCol_0.geometry} material={materials.VertexCol} />
          </group>
          <group position={[149.15, 0.39, -1158.74]} rotation={[-1.47, 0.01, 1.8]} scale={107.5}>
            <mesh geometry={nodes.Sclera002_ProceduralSclera001_0.geometry} material={materials['ProceduralSclera.001']} />
          </group>
          <group position={[149.15, 0.39, -1158.74]} rotation={[-1.47, 0.01, 1.8]} scale={107.5}>
            <mesh geometry={nodes.Iris002_VertexCol_0.geometry} material={materials.VertexCol} />
          </group>
          <group position={[149.15, 0.39, -1158.74]} rotation={[-1.47, 0.01, 1.8]} scale={107.5}>
            <mesh geometry={nodes.Highlight002_VertexCol_0.geometry} material={materials.VertexCol} />
          </group>
          <group position={[150, 0, -1150]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={107.5}>
            <mesh geometry={nodes.Shirt001_ProceduralFabricSmall_0.geometry} material={materials.ProceduralFabricSmall} />
          </group>
          <group position={[150, 0, -1150]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={107.5}>
            <mesh geometry={nodes.Shoes002_ProceduralFabricSmall_0.geometry} material={materials.ProceduralFabricSmall} />
          </group>
          <group position={[150, 0, -1150]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={107.5}>
            <mesh geometry={nodes.Coat001_ProceduralFabricSmall_0.geometry} material={materials.ProceduralFabricSmall} />
            <mesh geometry={nodes.Coat001_ProceduralFur_0.geometry} material={materials.ProceduralFur} />
          </group>
          <group position={[158.76, 0.65, -1161.78]} rotation={[-1.47, 0.01, 1.8]} scale={107.5}>
            <mesh geometry={nodes.HairMesh010_ProceduralHair_0.geometry} material={materials.ProceduralHair} />
          </group>
          <group position={[150, 0, -1150]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={107.5}>
            <mesh geometry={nodes.BoyBody002_ProceduralFabricSmall_0.geometry} material={materials.ProceduralFabricSmall} />
          </group>
          <group position={[125.17, -340.89, -1187.73]} rotation={[-1.47, 0.01, 1.8]} scale={312.48}>
            <mesh geometry={nodes.Glasses001_ProceduralMetal_0.geometry} material={materials.ProceduralMetal} />
            <mesh geometry={nodes.Glasses001_Glass_0.geometry} material={materials.Glass} />
          </group>
          <group position={[150, 0, -1250]} rotation={[-Math.PI / 2, 0, 0.56]} scale={100}>
            <mesh geometry={nodes.Dress002_ProceduralFabricSmall_0.geometry} material={materials.ProceduralFabricSmall} />
          </group>
          <group position={[150, 0, -1250]} rotation={[-Math.PI / 2, 0, 0.56]} scale={100}>
            <mesh geometry={nodes.Shoes004_ProceduralFabricSmall_0.geometry} material={materials.ProceduralFabricSmall} />
          </group>
          <group position={[150, 0, -1250]} rotation={[-Math.PI / 2, 0, 0.56]} scale={100}>
            <mesh geometry={nodes.Dress003_ProceduralFabricSmall_0.geometry} material={materials.ProceduralFabricSmall} />
          </group>
          <group position={[162.18, 1.01, -1252.33]} rotation={[-1.54, -0.12, 0.99]} scale={100}>
            <mesh geometry={nodes.Brow004_VertexCol_0.geometry} material={materials.VertexCol} />
          </group>
          <group position={[150, 0, -1250]} rotation={[-Math.PI / 2, 0, 0.56]} scale={100}>
            <mesh geometry={nodes.GirlBody002_ProceduralSkin_0.geometry} material={materials.ProceduralSkin} />
            <mesh geometry={nodes.GirlBody002_ProceduralHair_0.geometry} material={materials.ProceduralHair} />
          </group>
          <group position={[162.18, 1.01, -1252.33]} rotation={[-1.54, -0.12, 0.99]} scale={100}>
            <mesh geometry={nodes.Highlight004_Highlight_0.geometry} material={materials.Highlight} />
          </group>
          <group position={[162.18, 1.01, -1252.33]} rotation={[-1.54, -0.12, 0.99]} scale={100}>
            <mesh geometry={nodes.Iris004_VertexCol_0.geometry} material={materials.VertexCol} />
          </group>
          <group position={[162.18, 1.01, -1252.33]} rotation={[-1.54, -0.12, 0.99]} scale={100}>
            <mesh geometry={nodes.Sclera004_ProceduralSclera001_0.geometry} material={materials['ProceduralSclera.001']} />
          </group>
          <group position={[162.18, 1.01, -1252.33]} rotation={[-1.54, -0.12, 0.99]} scale={100}>
            <mesh geometry={nodes.Brow005_VertexCol_0.geometry} material={materials.VertexCol} />
          </group>
          <group position={[149.59, 0.86, -1250.67]} rotation={[-Math.PI / 2, 0, 0.56]} scale={100}>
            <mesh geometry={nodes.Plane012_ProceduralHair_0.geometry} material={materials.ProceduralHair} />
          </group>
          <group position={[182.59, -321.5, -1275.49]} rotation={[-1.54, -0.12, 0.99]} scale={290.68}>
            <mesh geometry={nodes.Glasses003_ProceduralMetal_0.geometry} material={materials.ProceduralMetal} />
            <mesh geometry={nodes.Glasses003_Glass_0.geometry} material={materials.Glass} />
          </group>
          <group position={[162.18, 1.01, -1252.33]} rotation={[-1.54, -0.12, 0.99]} scale={100}>
            <mesh geometry={nodes.Plane013_ProceduralFabricSmallReal_0.geometry} material={materials.ProceduralFabricSmallReal} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/parent.gltf')
