/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: scanontherun (https://sketchfab.com/scanontherun)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/person-bcd49ca3bcfb43739fd90a8dbfcf5319
title: Person
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'

export default function Model({...props}) {
	const group = useRef()
	const {nodes, materials} = useGLTF('/person1.gltf')
	return (
		<group ref={group} {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0.5]} position={[-1, 0.1, 3]}>
				<mesh geometry={nodes.Object_2.geometry} material={materials.material_0} />
				<mesh geometry={nodes.Object_3.geometry} material={materials.material_0} />
				<mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
				<mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
			</group>
		</group>
	)
}

useGLTF.preload('/person1.gltf')
